language: node_js
node_js: 
 - "8"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=jhonatan1967 -Dsonar.projectKey=jhonatan1967_micalc -Dsonar.sources='./app' -X